name: Bump OPA
on:
  push:
  schedule:
    - cron: '0 0 * * *' # run at 00:00 UTC
  workflow_dispatch:

jobs:
  versions:
    name: Detect versions
    runs-on: ubuntu-latest
    outputs:
      dopa_release: ${{ steps.extract.outputs.dopa_release }}
      opa_release: ${{ steps.extract.outputs.opa_release }}
    steps:
      - name: Get Latest OPA
        id: opa
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: open-policy-agent/opa
          excludes: prerelease, draft
      - uses: actions/checkout@v3 # TODO: replace this with a simple curl for the Directory.Build.props when things merged
      - name: Extract versions
        id: extract
        run: |
          echo "::set-output name=dopa_release::$(cat Directory.Build.props | grep -oP '>(.*)<\/OpaVersion>' | grep -oP '(\d.*\d)')"
          echo "::set-output name=opa_release::$(echo ${{ steps.opa.outputs.release }} | cut -d 'v' -f 2)"

  update:
    needs: versions
    if: ${{ needs.versions.outputs.dopa_release != needs.versions.outputs.opa_release }}
    name: Update DOPA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Update build props
        env:
          version: ${{ needs.versions.outputs.opa_release }}
        run: |
          sed "s/>.*<\/Opa/>${{ needs.versions.outputs.opa_release }}<\/Opa/" Directory.Build.props > out && mv out Directory.Build.props
          sed 's/<Revision>.*<\/Revision>/<Revision>0<\/Revision>/' Directory.Build.props > out && mv out Directory.Build.props
      - name: Pack targets
        run: dotnet pack -c release targets -o artifacts
      - name: Publish targets
        run: dotnet nuget push "artifacts/*" -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      - name: Create Pull Request For DOPA.Cli
        uses: peter-evans/create-pull-request@v4
        with:
          reviewers: willhausman
